kind: pipeline
type: docker
name: deploy production

steps:
  - name: deploy production
    image: appleboy/drone-ssh
    settings:
      host: deep-node.de
      username: pspenke
      port: 22
      key:
        from_secret: ssh_drone_key
      script:
        - cd /home/users/pspenke/www/onlineer-onepager/
        - git checkout main
        - git pull
        - yarn install --silent
        - yarn generate

trigger:
  branch:
  - main

